apiVersion: apps/v1
kind: Deployment
metadata:
  name: joy-tactics-app-deployment
  labels:
    app: joy-tactics-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: joy-tactics-app
  template:
    metadata:
      labels:
        app: joy-tactics-app
    spec:
      containers:
      - name: joy-tactics-app
        image: YOUR_DOCKER_USERNAME/joy-tactics-app
        ports:
        - containerPort: 8501
        env:
        - name: ES_HOSTNAME
          value: ES_HOSTNAME_VALUE
